version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
